# Translate acronyms from Yandex into full names for alt text
# Could instead use iso-639, but this works for now

from typing import Dict

languages: Dict[str, str] = {
    'hr': 'Croatian',
    'uk': 'Ukrainian',
    'fi': 'Finnish',
    'mk': 'Macedonian',
    'hy': 'Armenian',
    'sv': 'Swedish',
    'bg': 'Bulgarian',
    'ru': 'Russian',
    'hu': 'Hungarian',
    'pl': 'Polish',
    'el': 'Greek',
    'de': 'German',
    'tr': 'Turkish',
    'sl': 'Slovene',
    'es': 'Spanish',
    'en': 'English',
    'ca': 'Catalan',
    'pt': 'Portuguese',
    'cs': 'Czech',
    'nl': 'Dutch',
    'ro': 'Romanian',
    'sq': 'Albianian',
    'sk': 'Slovakian',
    'be': 'Belarusian',
    'sr': 'Serbian',
    'fr': 'French',
    'et': 'Estonian',
    'lv': 'Latvian',
    'it': 'Italian',
    'da': 'Danish',
    'no': 'Norwegian',
    'lt': 'Lithuanian',
    'az': 'Azerbaijani',
}
